chore: :rotating_light: Fix indentations
Signed-off-by: Javier J. Salmerón García <javier.salmeron@broadcom.com>

diff --git a/.vib/cloudnative-pg/runtime-parameters.yaml b/.vib/cloudnative-pg/runtime-parameters.yaml
--- a/.vib/cloudnative-pg/runtime-parameters.yaml
+++ b/.vib/cloudnative-pg/runtime-parameters.yaml
@@ -55,14 +55,14 @@ extraDeploy:
               echo 0 > /tmp/ready
               # Wait until the cluster is formed
               while true; do
-                if PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USER -d postgres -h vib-cluster-example-rw -c "SELECT client_addr, state FROM pg_stat_replication;" | grep "2 rows"; then
-                    echo 1 > /tmp/ready
-                    echo "Connected to PostgreSQL"
-                    break
-                else
-                    echo "Connection failed. Sleeping 10 seconds"
-                    sleep 10
-                fi
+                  if PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USER -d postgres -h vib-cluster-example-rw -c "SELECT client_addr, state FROM pg_stat_replication;" | grep "2 rows"; then
+                      echo 1 > /tmp/ready
+                      echo "Connected to PostgreSQL"
+                      break
+                  else
+                      echo "Connection failed. Sleeping 10 seconds"
+                      sleep 10
+                  fi
               done
               sleep infinity
           name: postgresql
@@ -84,9 +84,9 @@ extraDeploy:
                 - -c
                 - |
                   if [ $(cat /tmp/ready) = "1" ]; then
-                    exit 0
+                      exit 0
                   else
-                    exit 1
+                      exit 1
                   fi
             initialDelaySeconds: 40
             periodSeconds: 20
