[bitnami/redis] Rename variables
Signed-off-by: Aleh Yarmalovich <yarmolmi@gmail.com>

diff --git a/bitnami/redis/templates/scripts-configmap.yaml b/bitnami/redis/templates/scripts-configmap.yaml
--- a/bitnami/redis/templates/scripts-configmap.yaml
+++ b/bitnami/redis/templates/scripts-configmap.yaml
@@ -56,13 +56,13 @@ data:
         {{- else }}
         retry_count=0
         until getent hosts "${full_hostname}" | awk '{ print $1; exit }' | grep .; do 
-        if [[ $retry_count -lt {{ .Values.useHostnamesThreshold }} ]]; then
-            sleep {{ .Values.useHostnamesTimeout }}
-        else
-            error "IP address for ${full_hostname} not found"
-            exit 1
-        fi
-        ((retry_count++))
+            if [[ $retry_count -lt {{ .Values.nameResolutionThreshold }} ]]; then
+                sleep {{ .Values.nameResolutionTimeout }}
+            else
+                error "IP address for ${full_hostname} not found"
+                exit 1
+            fi
+            ((retry_count++))
         done
         {{- end }}
     }
@@ -289,13 +289,13 @@ data:
         {{- else }}
         retry_count=0
         until getent hosts "${full_hostname}" | awk '{ print $1; exit }' | grep .; do 
-        if [[ $retry_count -lt {{ .Values.useHostnamesThreshold }} ]]; then
-            sleep {{ .Values.useHostnamesTimeout }}
-        else
-            error "IP address for ${full_hostname} not found"
-            exit 1
-        fi
-        ((retry_count++))
+            if [[ $retry_count -lt {{ .Values.nameResolutionThreshold }} ]]; then
+                sleep {{ .Values.nameResolutionTimeout }}
+            else
+                error "IP address for ${full_hostname} not found"
+                exit 1
+            fi
+            ((retry_count++))
         done
         {{- end }}
     }
@@ -468,13 +468,13 @@ data:
         {{- else }}
         retry_count=0
         until getent hosts "${full_hostname}" | awk '{ print $1; exit }' | grep .; do 
-        if [[ $retry_count -lt {{ .Values.useHostnamesThreshold }} ]]; then
-            sleep {{ .Values.useHostnamesTimeout }}
-        else
-            error "IP address for ${full_hostname} not found"
-            exit 1
-        fi
-        ((retry_count++))
+            if [[ $retry_count -lt {{ .Values.nameResolutionThreshold }} ]]; then
+                sleep {{ .Values.nameResolutionTimeout }}
+            else
+                error "IP address for ${full_hostname} not found"
+                exit 1
+            fi
+            ((retry_count++))
         done
         {{- end }}
     }
@@ -550,13 +550,13 @@ data:
         {{- else }}
         retry_count=0
         until getent hosts "${full_hostname}" | awk '{ print $1; exit }' | grep .; do 
-        if [[ $retry_count -lt {{ .Values.useHostnamesThreshold }} ]]; then
-            sleep {{ .Values.useHostnamesTimeout }}
-        else
-            error "IP address for ${full_hostname} not found"
-            exit 1
-        fi
-        ((retry_count++))
+            if [[ $retry_count -lt {{ .Values.nameResolutionThreshold }} ]]; then
+                sleep {{ .Values.nameResolutionTimeout }}
+            else
+                error "IP address for ${full_hostname} not found"
+                exit 1
+            fi
+            ((retry_count++))
         done
         {{- end }}
     }
@@ -688,13 +688,13 @@ data:
         {{- else }}
         retry_count=0
         until getent hosts "${full_hostname}" | awk '{ print $1; exit }' | grep .; do 
-        if [[ $retry_count -lt {{ .Values.useHostnamesThreshold }} ]]; then
-            sleep {{ .Values.useHostnamesTimeout }}
-        else
-            error "IP address for ${full_hostname} not found"
-            exit 1
-        fi
-        ((retry_count++))
+            if [[ $retry_count -lt {{ .Values.nameResolutionThreshold }} ]]; then
+                sleep {{ .Values.nameResolutionTimeout }}
+            else
+                error "IP address for ${full_hostname} not found"
+                exit 1
+            fi
+            ((retry_count++))
         done
         {{- end }}
     }
