added ability to specify rs.conf settings

diff --git a/bitnami/mongodb/templates/replicaset/scripts-configmap.yaml b/bitnami/mongodb/templates/replicaset/scripts-configmap.yaml
--- a/bitnami/mongodb/templates/replicaset/scripts-configmap.yaml
+++ b/bitnami/mongodb/templates/replicaset/scripts-configmap.yaml
@@ -79,6 +79,13 @@ data:
     {{- end }}
     {{- end }}
 
+    {{- if .Values.replicaSetConfigurationSettings.enabled }}
+    # placed here before root password env is overwritten
+    # makes no assumption about starting state
+    # ensures that any stepDown or non-default starting state is handled
+    /scripts/replicaSetConfigurationSettings.sh &
+    {{- end }}
+
     echo "Advertised Hostname: $MONGODB_ADVERTISED_HOSTNAME"
 
     if [[ "$MY_POD_NAME" = "{{ $fullname }}-0" ]]; then
@@ -115,6 +122,14 @@ data:
     {{- end }}
     {{- end }}
     {{- end }}
+
+    {{- if .Values.replicaSetConfigurationSettings.enabled }}
+    # placed here before root password env is overwritten
+    # makes no assumption about starting state
+    # ensures that any stepDown or non-default starting state is handled
+    /scripts/replicaSetConfigurationSettings.sh &
+    {{- end }}
+
     echo "Advertised Hostname: $MONGODB_ADVERTISED_HOSTNAME"
     echo "Configuring node as a hidden node"
     export MONGODB_REPLICA_SET_MODE="hidden"
@@ -123,4 +138,67 @@ data:
     export MONGODB_ROOT_PASSWORD="" MONGODB_USERNAME="" MONGODB_DATABASE="" MONGODB_PASSWORD=""
     export MONGODB_ROOT_PASSWORD_FILE="" MONGODB_USERNAME_FILE="" MONGODB_DATABASE_FILE="" MONGODB_PASSWORD_FILE=""
     exec /opt/bitnami/scripts/mongodb/entrypoint.sh /opt/bitnami/scripts/mongodb/run.sh
+  {{- if .Values.replicaSetConfigurationSettings.enabled }}
+  replicaSetConfigurationSettings.sh: |-
+    #!/bin/bash
+    # This script to be called when pod starts.
+    # This script sets rs settings which can not be applied via conf file
+
+    function logger ()
+    #$1 is the line to be logged
+    {
+      echo "$(date -u)  replicaSetConfigurationSettings.sh -- ${1}" >&1
+    }
+
+    function killAllPids ()
+    {
+      logger "killAllPids function has been called"
+      for pid in $(ps -A -o pid | grep -v PID); do
+        kill -15 $pid
+      done
+    }
+
+    {{- if and .Values.auth.enabled .Values.auth.rootPassword}}
+    usernameAndPassword="-u root -p ${MONGODB_ROOT_PASSWORD}"
+    {{- else }}
+    usernameAndPassword=""
+    {{- end }}
+
+    SLEEP_PERIOD=10
+
+    # give the rs setup a chance to succeed before attempting to read or configure
+    sleep ${SLEEP_PERIOD}
+
+    # apply the settings only if this member is currently the mongo replicaset PRIMARY
+    # It might take a little time before any pod is PRIMARY
+    RS_MASTER_READ_RETRIES=5
+    counter=0
+    while ! mongo ${usernameAndPassword} --eval 'rs.isMaster()' | grep "ismaster\" : true"; do
+      logger "This node is not yet PRIMARY. Will check again in ${SLEEP_PERIOD} seconds. Retries remaining: $((${RS_MASTER_READ_RETRIES}-${counter}))"
+      counter=$((${counter} +1))
+      if [ ${counter} -gt ${RS_MASTER_READ_RETRIES} ]; then
+        logger "This node is not PRIMARY - waited $((${counter}*${SLEEP_PERIOD})) seconds"
+        logger "replicaSetConfigurationSettings will only be set on the member that is currently PRIMARY"
+        exit 0
+      fi
+      sleep ${SLEEP_PERIOD}
+    done   
+
+    logger "This node is currently PRIMARY - will apply rs.conf settings"
+
+    mongo ${usernameAndPassword} --eval 'cfg = rs.conf();
+      {{ range $setting, $value := .Values.replicaSetConfigurationSettings.configuration -}}
+        {{ printf "cfg.settings.%s = %v; " $setting $value }}
+      {{- end }}
+      rs.reconfig(cfg)'
+    if [ $? -ne 0 ]; then
+        logger "Failed to apply mongodb cfg.settings configuration"
+        killAllPids
+        exit 1
+    else 
+        logger "mongodb replicaset cfg.settings configuration applied"
+        mongo ${usernameAndPassword} --eval 'rs.conf()'
+    fi
+    exit
+  {{- end }}
 {{- end }}
