refectored much safer logic but untested

diff --git a/bitnami/mongodb/templates/replicaset/scripts-configmap.yaml b/bitnami/mongodb/templates/replicaset/scripts-configmap.yaml
--- a/bitnami/mongodb/templates/replicaset/scripts-configmap.yaml
+++ b/bitnami/mongodb/templates/replicaset/scripts-configmap.yaml
@@ -144,6 +144,8 @@ data:
     # This script to be called when pod starts.
     # This script sets rs settings which can not be applied via conf file
 
+    JSON_STRIPPER='s/\w+\([^)]+\)/null/g'
+
     function logger ()
     #$1 is the line to be logged
     {
@@ -157,7 +159,7 @@ data:
         kill -15 $pid
       done
     }
-
+  
     {{- if and .Values.auth.enabled .Values.auth.rootPassword}}
     usernameAndPassword="-u root -p ${MONGODB_ROOT_PASSWORD}"
     {{- else }}
@@ -166,39 +168,73 @@ data:
 
     SLEEP_PERIOD=10
 
-    # give the rs setup a chance to succeed before attempting to read or configure
-    sleep ${SLEEP_PERIOD}
+    
+    RS_CONF_READ_WRITE_ATTEMPTS=0
+    rs_conf_configured_ok=unknown
+    while $rs_conf_configured_ok -ne "true"; do
+      
+      # give the rs setup a chance to succeed before attempting to read or configure
+      sleep ${SLEEP_PERIOD}
+      
+      counter=0
+      while ! mongo ${usernameAndPassword} --eval 'rs.conf()'; do
+        counter=$((${counter} +1))
+        logger "not yet able to read rs.conf settings from the currently running rs. Tried ${counter} times."
+        sleep ${SLEEP_PERIOD}
+      done
+      
+      # can read rs.conf so read it again and store it
+      currentRsConf=$(mongo ${usernameAndPassword} --eval 'rs.conf()')
+      {{ range $setting, $value := .Values.replicaSetConfigurationSettings.configuration -}}
+      desiredRsConfList="{{ printf "%s:%v " $setting $value }}
+      {{- end }}"
+      # desiredRsConfList settings are a 'key:value' pair list, not an array which makes iterating and string manipulation very easy
+      # json format is '"<key>" : <value>,'
+      
+      desiredEqualsactual=unknown
+      for keyValue in "${desiredRsConfList}"; do
+        key=$(echo "${keyValue}" | awk -F: '{print $1}')
+        value=$(echo "${keyValue}" | awk -F: '{print $2}' | sed -E 's/[[:space:]]*$//')
+        if ! $(echo "\"${currentRsConf}"\" | grep -q -e "\"${key}\" : ${value},"); then
+           logger "current rs conf setting: ${key} value will be changed to: ${value}"
+           desiredEqualsactual=false
+        fi
+        else echo "current rs conf: ${key} is already at desired value: ${value}"
+      done
+
+    if [ ${desiredEqualsactual} -ne "false" ]; then
+      logger "replicaSetConfigurationSettings match the settings of the currently running rs"
+      rs_conf_configured_ok=true
+      exit
+    fi
 
     # apply the settings only if this member is currently the mongo replicaset PRIMARY
     # It might take a little time before any pod is PRIMARY
-    RS_MASTER_READ_RETRIES=5
-    counter=0
-    while ! mongo ${usernameAndPassword} --eval 'rs.isMaster()' | grep "ismaster\" : true"; do
-      logger "This node is not yet PRIMARY. Will check again in ${SLEEP_PERIOD} seconds. Retries remaining: $((${RS_MASTER_READ_RETRIES}-${counter}))"
-      counter=$((${counter} +1))
-      if [ ${counter} -gt ${RS_MASTER_READ_RETRIES} ]; then
-        logger "This node is not PRIMARY - waited $((${counter}*${SLEEP_PERIOD})) seconds"
-        logger "replicaSetConfigurationSettings will only be set on the member that is currently PRIMARY"
-        exit 0
-      fi
-      sleep ${SLEEP_PERIOD}
-    done   
-
-    logger "This node is currently PRIMARY - will apply rs.conf settings"
-
-    mongo ${usernameAndPassword} --eval 'cfg = rs.conf();
-      {{ range $setting, $value := .Values.replicaSetConfigurationSettings.configuration -}}
-        {{ printf "cfg.settings.%s = %v; " $setting $value }}
-      {{- end }}
-      rs.reconfig(cfg)'
-    if [ $? -ne 0 ]; then
-        logger "Failed to apply mongodb cfg.settings configuration"
-        killAllPids
-        exit 1
-    else 
-        logger "mongodb replicaset cfg.settings configuration applied"
-        mongo ${usernameAndPassword} --eval 'rs.conf()'
+    isMaster=unknown
+    if ! mongo ${usernameAndPassword} --eval 'rs.isMaster()' | grep "ismaster\" : true"; do
+      isMaster=false
+      logger "This node is not yet PRIMARY - replicaSetConfigurationSettings will only be set on the member that is currently PRIMARY"
+    else
+      isMaster=true
+      logger "This node is PRIMARY"
     fi
-    exit
+
+    if [ ${isMaster} -eq "true"]; then
+      logger "This node is currently PRIMARY - will apply rs.conf settings"
+
+      mongo ${usernameAndPassword} --eval 'cfg = rs.conf();
+        {{ range $setting, $value := .Values.replicaSetConfigurationSettings.configuration -}}
+          {{ printf "cfg.settings.%s = %v; " $setting $value }}
+        {{- end }}
+        rs.reconfig(cfg)'
+        RS_CONF_READ_WRITE_ATTEMPTS=$((${RS_CONF_READ_WRITE_ATTEMPTS} + 1 ))
+      if [ $? -ne 0 ]; then
+          logger "Failed to apply mongodb cfg.settings configuration"
+      else 
+          logger "mongodb replicaset cfg.settings configuration applied"
+          logger "Will check rs conf"
+          #don't exit just yet - it's worth double checking
+      fi
+    done  
   {{- end }}
 {{- end }}
