fix: :bug: Copy php var structure
Signed-off-by: Javier Salmeron Garcia <jsalmeron@vmware.com>

diff --git a/bitnami/phpmyadmin/templates/deployment.yaml b/bitnami/phpmyadmin/templates/deployment.yaml
--- a/bitnami/phpmyadmin/templates/deployment.yaml
+++ b/bitnami/phpmyadmin/templates/deployment.yaml
@@ -97,6 +97,11 @@ spec:
               if ! is_dir_empty /opt/bitnami/apache/logs; then
                 cp -r /opt/bitnami/apache/logs /emptydir/apache-logs-dir
               fi
+              info "Copying php var directory"
+              # PhpMyAdmin will fail to start if the php var folder is not populated
+              if ! is_dir_empty /opt/bitnami/php/var; then
+                cp -r /opt/bitnami/php/var /emptydir/php-var-dir
+              fi
               info "Copy operation completed"
           volumeMounts:
             - name: empty-dir
