Add configurable number of backups to keep
Signed-off-by: Erik Taylor <erikdvlp@outlook.com>

diff --git a/bitnami/postgresql/values.yaml b/bitnami/postgresql/values.yaml
--- a/bitnami/postgresql/values.yaml
+++ b/bitnami/postgresql/values.yaml
@@ -1298,6 +1298,8 @@ backup:
     failedJobsHistoryLimit: 1
     ## @param backup.cronjob.successfulJobsHistoryLimit Set the cronjob parameter successfulJobsHistoryLimit
     successfulJobsHistoryLimit: 3
+    ## @param backup.cronjob.backupsToKeep Set the cronjob parameter backupsToKeep
+    backupsToKeep: 5
     ## @param backup.cronjob.startingDeadlineSeconds Set the cronjob parameter startingDeadlineSeconds
     startingDeadlineSeconds: ""
     ## @param backup.cronjob.ttlSecondsAfterFinished Set the cronjob parameter ttlSecondsAfterFinished
@@ -1344,7 +1346,31 @@ backup:
     command:
       - /bin/sh
       - -c
-      - "pg_dumpall --clean --if-exists --load-via-partition-root --quote-all-identifiers --no-password --file=${PGDUMP_DIR}/pg_dumpall-$(date '+%Y-%m-%d-%H-%M').pgdump"
+      - |
+        BACKUP_DIR=${PGDUMP_DIR}
+        BACKUPS_TO_KEEP=${BACKUPS_TO_KEEP}
+        
+        echo "Current backups in ${BACKUP_DIR}:"
+        ls -lh ${BACKUP_DIR}/pg_dumpall-*.pgdump
+        
+        pg_dumpall --clean --if-exists --load-via-partition-root --quote-all-identifiers --no-password --file=${BACKUP_DIR}/pg_dumpall-$(date '+%Y-%m-%d-%H-%M').pgdump
+        
+        if [ $? -eq 0 ]; then
+          echo "Backup created successfully."
+          
+          BACKUPS_TO_DELETE=$(ls -1t $BACKUP_DIR/pg_dumpall-*.pgdump | tail -n +$((BACKUPS_TO_KEEP+1)))
+          
+          if [ -n "$BACKUPS_TO_DELETE" ]; then
+            echo "Deleting old backups:"
+            echo "$BACKUPS_TO_DELETE"
+            
+            echo "$BACKUPS_TO_DELETE" | xargs -I {} rm -- {}
+          else
+            echo "No backups to delete."
+          fi
+        else
+          echo "Backup creation failed. Old backups will not be deleted."
+        fi
     ## @param backup.cronjob.labels Set the cronjob labels
     labels: {}
     ## @param backup.cronjob.annotations Set the cronjob annotations
