[bitnami/etcd] Ensure disaster recovery snapshot script works.
Fixes #1921

diff --git a/bitnami/etcd/templates/scripts-configmap.yaml b/bitnami/etcd/templates/scripts-configmap.yaml
--- a/bitnami/etcd/templates/scripts-configmap.yaml
+++ b/bitnami/etcd/templates/scripts-configmap.yaml
@@ -254,14 +254,27 @@ data:
     AUTH_OPTIONS="{{ $etcdAuthOptions }}"
     ETCDCTL_ENDPOINTS="{{range $i, $e := until $replicaCount }}{{ $etcdClientProtocol }}://{{ $etcdFullname }}-{{ $e }}.{{ $etcdHeadlessServiceName }}.{{ $releaseNamespace }}.svc.{{ $clusterDomain }}:{{ $clientPort }},{{ end }}"
     # Remove the last comma "," introduced in the string
-    export ETCDCTL_ENDPOINTS="$(sed 's/,/ /g' <<< $ETCDCTL_ENDPOINTS | awk '{$1=$1};1' | sed 's/ /,/g')"
+    export ETCDCTL_ENDPOINTS="${ETCDCTL_ENDPOINTS%%,}"
+    # prepare space separated list of endpoints
+    export etcdctl_endpoints_list="$(sed 's/,/ /g' <<< $ETCDCTL_ENDPOINTS)"
 
     mkdir -p "/snapshots" 1>&3 2>&4
-    if etcdctl $AUTH_OPTIONS endpoint health; then
-        echo "Snapshotting the keyspace..." 1>&3 2>&4
-        etcdctl $AUTH_OPTIONS snapshot save "/snapshots/db" 1>&3 2>&4
-    else
-        echo "Cluster isn't responding!!" 1>&3 2>&4
-        exit 1
-    fi
+
+    # walk over each node in the list, check if node healthy make snapshot and exit, otherwise try another node
+    for etcd_endpoint in $etcdctl_endpoints_list; do
+        export ETCDCTL_ENDPOINTS="${etcd_endpoint}"
+        echo "Using etcd endpoint ${etcd_endpoint}" 1>&3 2>&4
+        if etcdctl $AUTH_OPTIONS endpoint health; then
+            echo "Snapshotting the keyspace..." 1>&3 2>&4
+            etcdctl $AUTH_OPTIONS snapshot save "/snapshots/db" 1>&3 2>&4
+            exit 0
+        else
+            echo "Warning - etcd endpoint not healthy ${etcd_endpoint}" 1>&3 2>&4
+            echo "Trying another endpoint." 1>&3 2>&4
+        fi
+    done
+
+    # exit with error if all endpoints are bad
+    echo "Error - all etcd endpoits are unhealthy!" 1>&3 2>&4
+    exit 1
 {{- end }}
