Remove unnecessary part

diff --git a/bitnami/redis-cluster/templates/update-cluster.yaml b/bitnami/redis-cluster/templates/update-cluster.yaml
--- a/bitnami/redis-cluster/templates/update-cluster.yaml
+++ b/bitnami/redis-cluster/templates/update-cluster.yaml
@@ -91,88 +91,58 @@ spec:
               if ! [[ -f /opt/bitnami/redis/etc/redis.conf ]]; then
                   cp /opt/bitnami/redis/etc/redis-default.conf /opt/bitnami/redis/etc/redis.conf
               fi
-              previous_node_ip=""
-              first_node_ip=$(wait_for_dns_lookup {{ template "common.names.fullname" . }}-0.{{ template "common.names.fullname" . }}-headless 120 5)
+              firstNodeIP=$(wait_for_dns_lookup {{ template "common.names.fullname" . }}-0.{{ template "common.names.fullname" . }}-headless 120 5)
               {{- if .Values.cluster.externalAccess.enabled }}
               newNodeCounter=0
-              for node_ip in $(echo "{{ .Values.cluster.update.newExternalIPs }}" | cut -d [ -f2 | cut -d ] -f 1 ); do
+              for nodeIP in $(echo "{{ .Values.cluster.update.newExternalIPs }}" | cut -d [ -f2 | cut -d ] -f 1 ); do
                 {{- if .Values.tls.enabled }}
-                while [[ $(redis-cli -h "$node_ip" -p "$REDIS_TLS_PORT" --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} ping) != 'PONG' ]]; do
+                while [[ $(redis-cli -h "$nodeIP" -p "$REDIS_TLS_PORT" --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} ping) != 'PONG' ]]; do
                 {{- else }}
-                while [[ $(redis-cli -h "$node_ip" -p "$REDIS_PORT" ping) != 'PONG' ]]; do
+                while [[ $(redis-cli -h "$nodeIP" -p "$REDIS_PORT" ping) != 'PONG' ]]; do
                 {{- end }}
-                  echo "Node $node_ip not ready, waiting for all the nodes to be ready..."
+                  echo "Node $nodeIP not ready, waiting for all the nodes to be ready..."
                   sleep 5
                 done
                 slave=()
                 if (( $REDIS_CLUSTER_REPLICAS >= 1 )) && (( newNodeCounter % (( $REDIS_CLUSTER_REPLICAS + 1 )) )); then
                   slave+=("--cluster-slave")
-                  [[ -z "$previous_node_ip" ]] && previous_node_ip=$first_node_ip
-                  if [[ -z "$REDISCLI_AUTH" ]]; then
-                    master_id=$(redis-cli -c -h $previous_node_ip cluster myid)
-                  else
-                    master_id=$(redis-cli -c -h $previous_node_ip -a $REDISCLI_AUTH cluster myid)
-                  fi
-                  slave+=("--cluster-master-id $master_id")
-                  echo "Adding Node ${newNodeCounter} ip: ${node_ip} as slave of ${master_id}"
-                else
-                  previous_node_ip=$node_ip
-                  echo "Adding Node ${newNodeCounter} ip: ${node_ip} as master"
                 fi
                 {{- if .Values.tls.enabled }}
-                while ! redis-cli --cluster --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} add-node "${node_ip}:${REDIS_TLS_PORT}" "{{ index .Values.cluster.externalAccess.service.loadBalancerIP 0 }}:${REDIS_TLS_PORT}" ${slave[@]}; do
+                while ! redis-cli --cluster --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} add-node "${nodeIP}:${REDIS_TLS_PORT}" "{{ index .Values.cluster.externalAccess.service.loadBalancerIP 0 }}:${REDIS_TLS_PORT}" ${slave[@]}; do
                 {{- else }}
-                while ! redis-cli --cluster add-node "${node_ip}:${REDIS_PORT}" "{{ index .Values.cluster.externalAccess.service.loadBalancerIP 0 }}:${REDIS_PORT}" ${slave[@]}; do
+                while ! redis-cli --cluster add-node "${nodeIP}:${REDIS_PORT}" "{{ index .Values.cluster.externalAccess.service.loadBalancerIP 0 }}:${REDIS_PORT}" ${slave[@]}; do
                 {{- end }}
-                  echo "Add-node ${new_node_index} ${new_node_ip} failed, retrying"
+                  echo "Add-node ${newNodeIndex} ${newNodeIP} failed, retrying"
                   sleep 5
                 done
                 ((newNodeCounter += 1))
               done
               {{- else }}
-              previous_node_index=""
               for node in $(seq $((1+{{ .Values.cluster.update.currentNumberOfNodes }})) {{ .Values.cluster.nodes }}); do
-                new_node_index="$(($node - 1))"
-                new_node_ip=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${new_node_index}.{{ template "common.names.fullname" . }}-headless" 120 5)
+                newNodeIndex="$(($node - 1))"
+                newNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${newNodeIndex}.{{ template "common.names.fullname" . }}-headless" 120 5)
                 {{- if .Values.tls.enabled }}
-                while [[ $(redis-cli -h "$new_node_ip" -p "$REDIS_TLS_PORT" --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} ping) != 'PONG' ]]; do
+                while [[ $(redis-cli -h "$newNodeIP" -p "$REDIS_TLS_PORT" --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} ping) != 'PONG' ]]; do
                 {{- else }}
-                while [[ $(redis-cli -h "$new_node_ip" -p "$REDIS_PORT" ping) != 'PONG' ]]; do
+                while [[ $(redis-cli -h "$newNodeIP" -p "$REDIS_PORT" ping) != 'PONG' ]]; do
                 {{- end }}
-                  echo "Node $new_node_ip not ready, waiting for all the nodes to be ready..."
-                  new_node_ip=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${new_node_index}.{{ template "common.names.fullname" . }}-headless" 120 5)
+                  echo "Node $newNodeIP not ready, waiting for all the nodes to be ready..."
+                  newNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${newNodeIndex}.{{ template "common.names.fullname" . }}-headless" 120 5)
                   sleep 5
                 done
                 slave=()
-                if (( $REDIS_CLUSTER_REPLICAS >= 1 )) && (( new_node_index % (( $REDIS_CLUSTER_REPLICAS + 1 )) )); then
+                if (( $REDIS_CLUSTER_REPLICAS >= 1 )) && (( newNodeIndex % (( $REDIS_CLUSTER_REPLICAS + 1 )) )); then
                   slave+=("--cluster-slave")
-                  if [[ -z "$previous_node_index" ]]; then
-                    previous_node_index=0
-                  fi
-                  master_id=""
-                  while [[ -z "$master_id" ]]; do
-                    previous_node_ip=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${previous_node_index}.{{ template "common.names.fullname" . }}-headless" 120 5)
-                    if [[ -z "$REDISCLI_AUTH" ]]; then
-                      master_id=$(redis-cli -c -h $previous_node_ip cluster myid)
-                    else
-                      master_id=$(redis-cli -c -h $previous_node_ip -a $REDISCLI_AUTH cluster myid)
-                    fi
-                  done
-                  slave+=("--cluster-master-id $master_id")
-                  echo "Adding Node $new_node_index ${new_node_ip} as slave of ${master_id}"
-                else
-                  previous_node_index=$new_node_index
-                  echo "Adding Node $new_node_index ${new_node_ip} as master"
                 fi
                 {{- if .Values.tls.enabled }}
-                while ! redis-cli --cluster add-node --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} "${new_node_ip}:${REDIS_TLS_PORT}" "${first_node_ip}:${REDIS_TLS_PORT}" ${slave[@]}; do
+                while ! redis-cli --cluster add-node --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} "${newNodeIP}:${REDIS_TLS_PORT}" "${firstNodeIP}:${REDIS_TLS_PORT}" ${slave[@]}; do
                 {{- else }}
-                while ! redis-cli --cluster add-node "${new_node_ip}:${REDIS_PORT}" "${first_node_ip}:${REDIS_PORT}" ${slave[@]}; do
+                while ! redis-cli --cluster add-node "${newNodeIP}:${REDIS_PORT}" "${firstNodeIP}:${REDIS_PORT}" ${slave[@]}; do
                 {{- end }}
-                  echo "Add-node ${new_node_index} ${new_node_ip} failed, retrying"
+                  echo "Add-node ${newNodeIndex} ${newNodeIP} failed, retrying"
                   sleep 5
-                  first_node_ip=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-0.{{ template "common.names.fullname" . }}-headless" 120 5)
-                  new_node_ip=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${new_node_index}.{{ template "common.names.fullname" . }}-headless" 120 5)
+                  firstNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-0.{{ template "common.names.fullname" . }}-headless" 120 5)
+                  newNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${newNodeIndex}.{{ template "common.names.fullname" . }}-headless" 120 5)
                 done
               done
               {{- end }}
