Use initContainer to configure keycloak certs
Signed-off-by: jgallucci32 <john.gallucci.iv@gmail.com>

diff --git a/bitnami/keycloak/templates/statefulset.yaml b/bitnami/keycloak/templates/statefulset.yaml
--- a/bitnami/keycloak/templates/statefulset.yaml
+++ b/bitnami/keycloak/templates/statefulset.yaml
@@ -62,8 +62,42 @@ spec:
       {{- if .Values.podSecurityContext.enabled }}
       securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
       {{- end }}
-      {{- if .Values.initContainers }}
+      {{- if or .Values.initContainers .Values.auth.tls.enabled }}
       initContainers: {{- include "common.tplvalues.render" (dict "value" .Values.initContainers "context" $) | nindent 8 }}
+      {{- end }}
+      {{- if .Values.auth.tls.enabled }}
+        - name: init-certs
+          image: busybox
+          imagePullPolicy: {{ .Values.image.pullPolicy }}
+          command:
+          - /bin/sh
+          - -c
+          - |-
+            ID="${MY_POD_NAME#${MY_INSTANCE_NAME}-}"
+            if [[ -f "/certs/keycloak.truststore.jks" ]] && [[ -f "/certs/keycloak-${ID}.keystore.jks" ]]; then
+                mkdir -p /opt/bitnami/keycloak/certs
+                cp "/certs/keycloak.truststore.jks" "/opt/bitnami/keycloak/certs/keycloak.truststore.jks"
+                cp "/certs/keycloak-${ID}.keystore.jks" "/opt/bitnami/keycloak/certs/keycloak.keystore.jks"
+            else
+                echo "Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled."
+                exit 1
+            fi
+          env:
+          - name: MY_INSTANCE_NAME
+            valueFrom:
+              fieldRef:
+                apiVersion: v1
+                fieldPath: metadata.labels['app.kubernetes.io/instance']
+          - name: MY_POD_NAME
+            valueFrom:
+              fieldRef:
+                apiVersion: v1
+                fieldPath: metadata.name
+          volumeMounts:
+          - name: certificates
+            mountPath: /certs
+          - name: shared-certs
+            mountPath: /opt/bitnami/keycloak/certs
       {{- end }}
       containers:
         - name: keycloak
@@ -77,31 +111,11 @@ spec:
           {{- end }}
           {{- if .Values.command }}
           command: {{- include "common.tplvalues.render" (dict "value" .Values.command "context" $) | nindent 12 }}
-          {{- else if .Values.auth.tls.enabled }}
-          {{- $fullname := include "keycloak.fullname" . }}
-          command:
-            - /bin/bash
-            - -ec
-            - |
-              ID="${MY_POD_NAME#"{{ $fullname }}-"}"
-              if [[ -f "/certs/keycloak.truststore.jks" ]] && [[ -f "/certs/keycloak-${ID}.keystore.jks" ]]; then
-                  mkdir -p /opt/bitnami/keycloak/certs
-                  cp "/certs/keycloak.truststore.jks" "/opt/bitnami/keycloak/certs/keycloak.truststore.jks"
-                  cp "/certs/keycloak-${ID}.keystore.jks" "/opt/bitnami/keycloak/certs/keycloak.keystore.jks"
-              else
-                  echo "Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled."
-                  exit 1
-              fi
-              exec /opt/bitnami/scripts/keycloak/entrypoint.sh /opt/bitnami/scripts/keycloak/run.sh
           {{- end }}
           {{- if .Values.args }}
           args: {{- include "common.tplvalues.render" (dict "value" .Values.args "context" $) | nindent 12 }}
           {{- end }}
           env:
-            - name: MY_POD_NAME
-              valueFrom:
-                fieldRef:
-                  fieldPath: metadata.name
             - name: KUBERNETES_NAMESPACE
               valueFrom:
                 fieldRef:
@@ -189,8 +203,8 @@ spec:
               subPath: standalone-ha.xml
             {{- end }}
             {{- if .Values.auth.tls.enabled }}
-            - name: certificates
-              mountPath: /certs
+            - name: shared-certs
+              mountPath: /opt/bitnami/keycloak/certs
               readOnly: true
             {{- end }}
             {{- if or .Values.initdbScriptsConfigMap .Values.initdbScripts }}
@@ -214,6 +228,8 @@ spec:
           secret:
             secretName: {{ printf "%s" (tpl .Values.auth.tls.jksSecret $) }}
             defaultMode: 256
+        - name: shared-certs
+          emptyDir: {}
         {{- end }}
         {{- if or .Values.initdbScriptsConfigMap .Values.initdbScripts }}
         - name: custom-init-scripts
