Using comm to show missing URLs
Co-authored-by: Alejandro Ruiz <4057165+aruiz14@users.noreply.github.com>
Signed-off-by: Roberto Andradas <randradas@vmware.com>

diff --git a/.github/workflows/archive-full-index.yaml b/.github/workflows/archive-full-index.yaml
--- a/.github/workflows/archive-full-index.yaml
+++ b/.github/workflows/archive-full-index.yaml
@@ -105,7 +105,11 @@ jobs:
         run: |
           yq eval '.entries[][].urls[]' last_index.yaml |sort| uniq > last_index_urls
           yq eval '.entries[][].urls[]' index.yaml | sort| uniq > index_urls
-          for i in `cat last_index_urls`; do  grep -q $i index_urls || exit 1 ; done
+          missing_urls="$(comm -13 index_urls last_index_urls)"
+          if [ -n "${missing_urls}" ]; then
+              echo "Found missing URLs:\n${missing_urls}"
+              exit 1
+          fi
           echo "No missing releases detected"
   update:
     runs-on: ubuntu-latest
