Change bitnami folder & bitnami org references to "charts" or "cloudcops"

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -11,7 +11,7 @@ on: # rebuild any PRs and main branch changes
       - labeled
     branches:
       - main
-      - bitnami:main
+      - cloudcops:main
 # Remove all permissions by default
 permissions: {}
 # Avoid concurrency over the same PR
@@ -39,10 +39,10 @@ jobs:
           files_changed_data="$(gh api --paginate "/repos/${GITHUB_REPOSITORY}/pulls/${PULL_REQUEST_NUMBER}/files")"
           files_changed="$(echo "$files_changed_data" | jq -r '.[] | .filename')"
           # Adding || true to avoid "Process exited with code 1" errors
-          charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep -o "bitnami/[^/]*" | sort | uniq || true)"
+          charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep -o "charts/[^/]*" | sort | uniq || true)"
           # Using grep -c as a better alternative to wc -l when dealing with empty strings."
-          num_charts_changed="$(echo "$charts_dirs_changed" | grep -c "bitnami" || true)"
-          num_version_bumps="$(echo "$files_changed_data" | jq -r '[.[] | select(.filename|match("bitnami/[^/]+/Chart.yaml")) | select(.patch|contains("+version")) ] | length' )"
+          num_charts_changed="$(echo "$charts_dirs_changed" | grep -c "charts" || true)"
+          num_version_bumps="$(echo "$files_changed_data" | jq -r '[.[] | select(.filename|match("charts/[^/]+/Chart.yaml")) | select(.patch|contains("+version")) ] | length' )"
           non_readme_files=$(echo "$files_changed" | grep -vc "\.md" || true)
 
           if [[ $(curl -Lks "${PULL_REQUEST_URL}" | jq '.state | index("closed")') != *null* ]]; then
@@ -60,15 +60,15 @@ jobs:
             # Changes done in only one chart -> OK
             echo "result=ok" >> "$GITHUB_OUTPUT"
             # Extra output: chart name
-            chart_name="${charts_dirs_changed//bitnami\/}"
+            chart_name="${charts_dirs_changed//charts\/}"
             echo "chart=${chart_name}" >> "$GITHUB_OUTPUT"
             # Extra output: values-updated
             # shellcheck disable=SC2076
-            if [[ "${files_changed[*]}" =~ "bitnami/${chart_name}/values.yaml" ]]; then
+            if [[ "${files_changed[*]}" =~ "charts/${chart_name}/values.yaml" ]]; then
               echo "values-updated=true" >> "$GITHUB_OUTPUT"
             fi
           elif [[ "$num_charts_changed" -le "0" ]]; then
-            # Changes done in the bitnami/ folder but not inside a chart subfolder -> SKIP
+            # Changes done in the charts/ folder but not inside a chart subfolder -> SKIP
             echo "error=No changes detected in charts. The rest of the tests will be skipped." >> "$GITHUB_OUTPUT"
             echo "result=skip" >> "$GITHUB_OUTPUT"
           else
@@ -96,7 +96,7 @@ jobs:
     name: Look for hardcoded images
     if: needs.get-chart.outputs.result == 'ok'
     steps:
-      - name: Checkout bitnami/charts
+      - name: Checkout cloudcops/charts
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
         with:
           ref: ${{github.event.pull_request.head.ref}}
@@ -114,7 +114,7 @@ jobs:
             if [[ -n "$image" && $image != {{*}} ]]; then
               hardcoded_images+=("${image}")
             fi
-          done <<< "$(grep --exclude "NOTES.txt" -REoh "\s*image:\s+[\"']*.+[\"']*\s*$" "bitnami/${CHART}/templates" | sed "s/image: [\"']*//" | sed "s/[\"']*$//")"
+          done <<< "$(grep --exclude "NOTES.txt" -REoh "\s*image:\s+[\"']*.+[\"']*\s*$" "charts/${CHART}/templates" | sed "s/image: [\"']*//" | sed "s/[\"']*$//")"
           echo "${hardcoded_images[@]}"
           if [[ ${#hardcoded_images[@]} -gt 0 ]] ; then
             echo "error=Found hardcoded images in the chart templates: ${hardcoded_images[*]}"
@@ -128,8 +128,8 @@ jobs:
           cd "${GITHUB_WORKSPACE}/charts" || exit 1
 
           if [[ "$CHART" != "common" && "$CHART" != "fluentd" ]]; then
-            readarray -t tag_paths < <(yq e '.. | (path | join("."))' "bitnami/${CHART}/values.yaml" | grep -E '\.tag$' | sed 's/.tag$//g' | sort -u)
-            readarray -t registry_paths < <(yq e '.. | (path | join("."))' "bitnami/${CHART}/values.yaml" | grep '\.registry$' | sed 's/.registry$//g' | sort -u)
+            readarray -t tag_paths < <(yq e '.. | (path | join("."))' "charts/${CHART}/values.yaml" | grep -E '\.tag$' | sed 's/.tag$//g' | sort -u)
+            readarray -t registry_paths < <(yq e '.. | (path | join("."))' "charts/${CHART}/values.yaml" | grep '\.registry$' | sed 's/.registry$//g' | sort -u)
 
             # We assume that image objects are those that contain both keys 'tag' and 'registry'
             images_paths=()
@@ -140,7 +140,7 @@ jobs:
             done
 
             # Get the images defined in the image warning helper
-            readarray -d ' ' -t images_list_tmp < <(grep -E 'common.warnings.modifiedImages' "bitnami/${CHART}/templates/NOTES.txt" | sed -E 's/.*\(list (.+)\) "context".*/\1/' | sed 's/.Values.//g')
+            readarray -d ' ' -t images_list_tmp < <(grep -E 'common.warnings.modifiedImages' "charts/${CHART}/templates/NOTES.txt" | sed -E 's/.*\(list (.+)\) "context".*/\1/' | sed 's/.Values.//g')
 
             # Remove any empty element from the array
             images_list=()
@@ -173,14 +173,14 @@ jobs:
       result: ${{ steps.update-pr.outputs.result }}
     if: needs.get-chart.outputs.result == 'ok'
     steps:
-      - name: Checkout bitnami/charts
+      - name: Checkout cloudcops/charts
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
         with:
           ref: ${{github.event.pull_request.head.ref}}
           repository: ${{github.event.pull_request.head.repo.full_name}}
           token: ${{ secrets.BITNAMI_BOT_TOKEN }}
           path: charts
-      - name: Clone upstream bitnami/charts repository
+      - name: Clone upstream cloudcops/charts repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
         with:
           path: upstream-charts
@@ -212,11 +212,11 @@ jobs:
           # Get PR title using the API to avoid malicious string substitutions
           pr_title="$(gh api "/repos/${GITHUB_REPOSITORY}/pulls/${PULL_REQUEST_NUMBER}" | jq -r '.title')"
           # The generator needs the file to exist
-          chart_version="$(yq e '.version' "${GITHUB_WORKSPACE}/charts/bitnami/${CHART}/Chart.yaml")"
-          changelog_file="${GITHUB_WORKSPACE}/charts/bitnami/${CHART}/CHANGELOG.md"
-          changelog_tmp="${GITHUB_WORKSPACE}/charts/bitnami/${CHART}/CHANGELOG.md.tmp"
+          chart_version="$(yq e '.version' "${GITHUB_WORKSPACE}/charts/charts/${CHART}/Chart.yaml")"
+          changelog_file="${GITHUB_WORKSPACE}/charts/charts/${CHART}/CHANGELOG.md"
+          changelog_tmp="${GITHUB_WORKSPACE}/charts/charts/${CHART}/CHANGELOG.md.tmp"
           touch "$changelog_file"
-          npx conventional-changelog-cli -i "$changelog_file" -s -t "${CHART}/" -r 0 --commit-path "bitnami/${CHART}"
+          npx conventional-changelog-cli -i "$changelog_file" -s -t "${CHART}/" -r 0 --commit-path "charts/${CHART}"
           # The tool uses short sha to generate commit links. Sometimes, Github does not offer links with the short sha, so we change all commit links to use the full sha instead
           for short_sha in $(grep -Eo "/commit/[a-z0-9]+" "$changelog_file" | awk -F/ '{print $3}'); do
             long_sha="$(git rev-list @ | grep "^$short_sha" | head -n 1)";
@@ -238,8 +238,8 @@ jobs:
           rm "$changelog_tmp"
 
           # Commit all changes, if any
-          if git status -s | grep "bitnami/${CHART}/CHANGELOG.md"; then
-            git add "bitnami/${CHART}/CHANGELOG.md"
+          if git status -s | grep "charts/${CHART}/CHANGELOG.md"; then
+            git add "charts/${CHART}/CHANGELOG.md"
             git commit -m "Update CHANGELOG.md" --signoff
           fi
       - name: Install readme-generator-for-helm
@@ -254,14 +254,14 @@ jobs:
           exit_code=0
           cd "${GITHUB_WORKSPACE}/charts" || exit 1
 
-          echo "Validating README.md for bitnami/${CHART}"
+          echo "Validating README.md for charts/${CHART}"
 
           # Validating *.registry parameters
           while read -r line; do
             echo "$line" | grep --quiet "\[default: \(REGISTRY_NAME\|\"\"\)\]" || exit_code=$?
-          done < <(grep "@param\s\+[A-Za-z\.]\+\.registry\s\+" "bitnami/${CHART}/values.yaml")
+          done < <(grep "@param\s\+[A-Za-z\.]\+\.registry\s\+" "charts/${CHART}/values.yaml")
           if [[ $exit_code -ne 0 ]]; then
-            echo "error=Please ensure all *.registry params include the [default: REGISTRY_NAME] modifier in the chart bitnami/${CHART}/values.yaml file"
+            echo "error=Please ensure all *.registry params include the [default: REGISTRY_NAME] modifier in the chart charts/${CHART}/values.yaml file"
             exit "$exit_code"
           fi
 
@@ -270,25 +270,25 @@ jobs:
             param=$(echo "$line" | awk '{print $3}')
             # Checking if it's a image's registry-related param
             registry_param="${param//.repository/.registry}"
-            grep --quiet "@param\s\+${registry_param}" "bitnami/${CHART}/values.yaml" && ( echo "$line" | grep --quiet "\[default: \(REPOSITORY_NAME/.*\|\"\"\)\]" || exit_code=$? )
-          done < <(grep "@param\s\+[A-Za-z\.]\+\.repository\s\+" "bitnami/${CHART}/values.yaml")
+            grep --quiet "@param\s\+${registry_param}" "charts/${CHART}/values.yaml" && ( echo "$line" | grep --quiet "\[default: \(REPOSITORY_NAME/.*\|\"\"\)\]" || exit_code=$? )
+          done < <(grep "@param\s\+[A-Za-z\.]\+\.repository\s\+" "charts/${CHART}/values.yaml")
           if [[ $exit_code -ne 0 ]]; then
-            echo "error=Please ensure all *.repository params include the [default: REPOSITORY_NAME] modifier the in the chart bitnami/${CHART}/values.yaml file"
+            echo "error=Please ensure all *.repository params include the [default: REPOSITORY_NAME] modifier the in the chart charts/${CHART}/values.yaml file"
             exit "$exit_code"
           fi
 
           # Validating *.tag parameters
-          grep -v --quiet "@param\s\+[A-Za-z\.]\+\.tag\s\+" "bitnami/${CHART}/values.yaml" || exit_code=$?
+          grep -v --quiet "@param\s\+[A-Za-z\.]\+\.tag\s\+" "charts/${CHART}/values.yaml" || exit_code=$?
           if [[ $exit_code -ne 0 ]]; then
-            echo "error=Please ensure all *.tag params are skipped (@skip) in the bitnami/${CHART}/values.yaml file"
+            echo "error=Please ensure all *.tag params are skipped (@skip) in the charts/${CHART}/values.yaml file"
             exit "$exit_code"
           fi
-          echo "Updating README.md for bitnami/${CHART}"
-          readme-generator --values "bitnami/${CHART}/values.yaml" --readme "bitnami/${CHART}/README.md" --schema "/tmp/schema.json"
+          echo "Updating README.md for charts/${CHART}"
+          readme-generator --values "charts/${CHART}/values.yaml" --readme "charts/${CHART}/README.md" --schema "/tmp/schema.json"
 
           # Commit all changes, if any
-          if git status -s | grep "bitnami/${CHART}"; then
-            git add "bitnami/${CHART}"
+          if git status -s | grep "charts/${CHART}"; then
+            git add "charts/${CHART}"
             git commit -m "Update README.md with readme-generator-for-helm" --signoff
           fi
       - id: update-crds
@@ -300,8 +300,8 @@ jobs:
         run: |
           cd "${GITHUB_WORKSPACE}/charts" || exit 1
 
-          # Updating CRDs stored at 'bitnami/$CHART/crds', 'bitnami/$CHART/templates/crds', and "bitnami/${CHART}/charts/${CHART}-crds/crds"
-          mapfile -t crd_files < <(find "bitnami/${CHART}/crds" "bitnami/${CHART}/templates/crds" "bitnami/${CHART}/charts/${CHART}-crds/crds" -name "*.yaml" -o -name "*.yml" 2>/dev/null || true)
+          # Updating CRDs stored at 'charts/$CHART/crds', 'charts/$CHART/templates/crds', and "charts/${CHART}/charts/${CHART}-crds/crds"
+          mapfile -t crd_files < <(find "charts/${CHART}/crds" "charts/${CHART}/templates/crds" "charts/${CHART}/charts/${CHART}-crds/crds" -name "*.yaml" -o -name "*.yml" 2>/dev/null || true)
           for file in "${crd_files[@]}"; do
             # Automatically update CRDs that use the '# Source' header
             source_url_tpl="$(head -n 1 "$file" | grep -E "^# ?Source: ?" | sed -E 's|^# ?Source: ?||' || true)"
@@ -348,9 +348,9 @@ jobs:
               done
               # Obtain the version of the subcomponent if provided, otherwise use the main component version
               if [[ -n "$SUBCOMPONENT" ]]; then
-                APP_VERSION="$(cat bitnami/${CHART}/Chart.yaml | grep -E "image: \S+${SUBCOMPONENT}:" | sed -E "s|.*${SUBCOMPONENT}:([0-9\.]+)-.*|\1|")"
+                APP_VERSION="$(cat charts/${CHART}/Chart.yaml | grep -E "image: \S+${SUBCOMPONENT}:" | sed -E "s|.*${SUBCOMPONENT}:([0-9\.]+)-.*|\1|")"
               else
-                APP_VERSION="$(yq e '.appVersion' bitnami/${CHART}/Chart.yaml)"
+                APP_VERSION="$(yq e '.appVersion' charts/${CHART}/Chart.yaml)"
               fi
               # Replace version placeholder, if present
               source_url=$(echo "$source_url_tpl" | sed "s/{version}/${APP_VERSION}/")
@@ -376,8 +376,8 @@ jobs:
           done
 
           # Commit all changes, if any
-          if git status -s | grep "bitnami/${CHART}"; then
-            git add "bitnami/${CHART}"
+          if git status -s | grep "charts/${CHART}"; then
+            git add "charts/${CHART}"
             git commit -m "Update CRDs automatically" --signoff
           fi
       - id: update-prometheus-rules
@@ -419,8 +419,8 @@ jobs:
             esac
           }
 
-          mkdir -p "bitnami/kube-prometheus/templates/prometheus/rules"
-          cd "bitnami/kube-prometheus/templates/prometheus/rules"
+          mkdir -p "charts/kube-prometheus/templates/prometheus/rules"
+          cd "charts/kube-prometheus/templates/prometheus/rules"
           helm repo add prometheus-community https://prometheus-community.github.io/helm-charts 2>&1 >/dev/null 2>&1
           helm repo update >/dev/null 2>&1
           helm template prometheus-community/kube-prometheus-stack \
@@ -458,8 +458,8 @@ jobs:
           done
 
           cd "${GITHUB_WORKSPACE}/charts"
-          if git status -s | grep "bitnami/kube-prometheus/templates/prometheus/rules"; then
-            git add "bitnami/kube-prometheus/templates/prometheus/rules"
+          if git status -s | grep "charts/kube-prometheus/templates/prometheus/rules"; then
+            git add "charts/kube-prometheus/templates/prometheus/rules"
             git commit -m "Update Prometheus rules" --signoff
           fi
       - id: update-pr
@@ -487,7 +487,7 @@ jobs:
         name: Checkout 'main' branch
         with:
           path: charts-main
-          repository: bitnami/charts
+          repository: cloudcops/charts
           fetch-depth: 1
       - name: Install helm
         run: |
@@ -497,10 +497,10 @@ jobs:
         env:
           CHART: ${{ needs.get-chart.outputs.chart }}
         run: |
-          if [ -d "charts-main/bitnami/${CHART}" ]; then
-            helm dep build charts-main/bitnami/${CHART}
-            if [ -d "charts-main/bitnami/${CHART}/charts" ]; then
-              cd charts-main/bitnami/${CHART}/charts
+          if [ -d "charts-main/charts/${CHART}" ]; then
+            helm dep build charts-main/charts/${CHART}
+            if [ -d "charts-main/charts/${CHART}/charts" ]; then
+              cd charts-main/charts/${CHART}/charts
               for filename in *.tgz; do
                 tar -xf "$filename"
                 rm -f "$filename"
@@ -523,12 +523,12 @@ jobs:
           image: bitnami/kubescape:3.0.3
           options: -v  /home/runner/work/charts/charts/charts-main:/charts -v /tmp:/out -e CHART
           run: |
-            if [ -d "/charts/bitnami/${CHART}" ]; then
-              kubescape scan framework MITRE,NSA,SOC2,cis-v1.23-t1.0.1 /charts/bitnami/${CHART} --format json -o /out/report.json
+            if [ -d "/charts/charts/${CHART}" ]; then
+              kubescape scan framework MITRE,NSA,SOC2,cis-v1.23-t1.0.1 /charts/charts/${CHART} --format json -o /out/report.json
               # Truncate score to 2 decimals
               printf "%s.%.2s" $(echo "$(jq .summaryDetails.complianceScore /out/report.json)" | tr '.' ' ') | sed 's/\.$//' > /out/score
             else
-              echo "Chart not found at /charts/bitnami/${CHART}. It will be assumed that the upstream chart does not exist."
+              echo "Chart not found at /charts/charts/${CHART}. It will be assumed that the upstream chart does not exist."
             fi
       - id: set-output
         name: Set threshold score
@@ -570,8 +570,8 @@ jobs:
           CHART: ${{ needs.get-chart.outputs.chart }}
         run: |
           # Log chart info
-          chart_version="$(yq e '.version' bitnami/${CHART}/Chart.yaml)"
-          app_version="$(yq e '.appVersion' bitnami/${CHART}/Chart.yaml)"
+          chart_version="$(yq e '.version' charts/${CHART}/Chart.yaml)"
+          app_version="$(yq e '.appVersion' charts/${CHART}/Chart.yaml)"
           echo "Chart: ${CHART} ChartVersion: ${chart_version} AppVersion: ${app_version}"
       - id: get-asset-vib-config
         name: Get asset-specific configuration for VIB action
