Update CI pipeline
Signed-off-by: Miguel Ruiz <miruiz@vmware.com>

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -24,8 +24,10 @@ jobs:
     permissions:
       pull-requests: read
     outputs:
+      app-version: ${{ steps.get-chart.outputs.app-version }}
       chart: ${{ steps.get-chart.outputs.chart }}
       result: ${{ steps.get-chart.outputs.result }}
+      values-updated: ${{ steps.get-chart.outputs.values-updated }}
     steps:
       - id: get-chart
         name: Get modified charts
@@ -57,9 +59,17 @@ jobs:
             echo "result=fail" >> $GITHUB_OUTPUT
           elif [[ "$num_charts_changed" -eq "1" ]]; then
             # Changes done in only one chart -> OK
+            # Extra output: app-version
+            app-version="$(yq e '.appVersion' bitnami/${CHART}/Chart.yaml)"
+            echo "app-version=${app-version}" >> $GITHUB_OUTPUT
+            # Extra output: chart name
             chart_name=$(echo "$charts_dirs_changed" | sed "s|bitnami/||g")
             echo "chart=${chart_name}" >> $GITHUB_OUTPUT
             echo "result=ok" >> $GITHUB_OUTPUT
+            # Extra output: values-updated
+            if [[ ${files_changed[@]} =~ "bitnami/${chart_name}/values.yaml" ]]; then
+              echo "values-updated=true" >> $GITHUB_OUTPUT
+            fi
           elif [[ "$num_charts_changed" -le "0" ]]; then
             # Changes done in the bitnami/ folder but not inside a chart subfolder -> SKIP
             echo "error=No changes detected in charts. The rest of the tests will be skipped." >> $GITHUB_OUTPUT
@@ -83,16 +93,146 @@ jobs:
             } else {
               core.warning(message);
             }
+  update-pr:
+    runs-on: ubuntu-latest
+    needs: [get-chart]
+    name: Automatically update README and CRDs
+    permissions:
+      contents: read
+      pull-requests: write
+    outputs:
+      changes-pushed: ${{ steps.update-pr.outputs.changes-pushed }}
+    if: |
+      needs.get-chart.outputs.result == 'ok'
+    steps:
+      - name: Checkout bitnami/charts
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
+        with:
+          ref: ${{github.event.pull_request.head.ref}}
+          repository: ${{github.event.pull_request.head.repo.full_name}}
+          token: ${{ github.actor == 'bitnami-bot' && secrets.GITHUB_TOKEN || secrets.BITNAMI_BOT_TOKEN }}
+      - name: Setup git configuration
+        run: |
+          git config user.name "Bitnami Containers"
+          git config user.email "bitnami-bot@vmware.com"
+      - name: Install readme-generator-for-helm
+        run: |
+          if [[ "$VALUES_UPDATED" == "true" ]]; then
+            npm install -g @bitnami/readme-generator-for-helm
+          fi
+      - id: update-readme
+        name: 'Update README'
+        env:
+          CHART: ${{ needs.get-chart.outputs.chart }}
+          VALUES_UPDATED: ${{ needs.get-chart.outputs.values-updated }}
+        run: |
+            exit_code=0
+            if [[ "$VALUES_UPDATED" == "true" ]]; then
+              echo "Validating README.md for bitnami/${CHART}"
+              # Validating *.registry parameters
+              while read line; do
+                echo "$line" | grep --quiet "\[default: \(REGISTRY_NAME\|\"\"\)\]" || exit_code=$?
+              done < <(grep "@param\s\+[A-Za-z\.]\+\.registry\s\+" "bitnami/${CHART}/values.yaml")
+              if [[ $exit_code -ne 0 ]]; then
+                echo "error=Please ensure all *.registry params include the [default: REGISTRY_NAME] modifier in the chart bitnami/${CHART}/values.yaml file"
+                exit "$exit_code"
+              fi
+              # Validating *.repository parameters
+              while read line; do
+                param=$(echo "$line" | awk '{print $3}')
+                # Checking if it's a image's registry-related param
+                registry_param=$(echo ${param} | sed 's/\.repository/\.registry/g')
+                grep --quiet "@param\s\+${registry_param}" "bitnami/${CHART}/values.yaml" && ( echo "$line" | grep --quiet "\[default: \(REPOSITORY_NAME/.*\|\"\"\)\]" || exit_code=$? )
+              done < <(grep "@param\s\+[A-Za-z\.]\+\.repository\s\+" "bitnami/${CHART}/values.yaml")
+              if [[ $exit_code -ne 0 ]]; then
+                echo "error=Please ensure all *.repository params include the [default: REPOSITORY_NAME] modifier the in the chart bitnami/${CHART}/values.yaml file"
+                exit "$exit_code"
+              fi
+              # Validating *.tag parameters
+              ! grep --quiet "@param\s\+[A-Za-z\.]\+\.tag\s\+" "bitnami/${CHART}/values.yaml" || exit_code=$?
+              if [[ $exit_code -ne 0 ]]; then
+                echo "error=Please ensure all *.tag params are skipped (@skip) in the bitnami/${CHART}/values.yaml file"
+                exit "$exit_code"
+              fi
+              echo "Updating README.md for bitnami/${CHART}"
+              readme-generator --values "bitnami/${CHART}/values.yaml" --readme "bitnami/${CHART}/README.md" --schema "/tmp/schema.json"
+              # Commit all changes, if any
+              if git status -s | grep "bitnami/${CHART}"; then
+                git add "bitnami/${CHART}" && git commit -m "Update README.md with readme-generator-for-helm" --signoff
+              fi
+            fi
+      - id: update-crds
+        name: 'Update CRDs'
+        env:
+          CHART: ${{ needs.get-chart.outputs.chart }}
+          APP_VERSION: ${{ needs.get-chart.outputs.app-version }}
+          TEMP_DIR: "${{runner.temp}}"
+          PR_USER: "${{github.event.pull_request.user.login}}"
+        run: |
+          # To avoid malicious executions, only PRs performed by the bitnami-bot will perform the CRDs update
+          if [[ "$PR_USER" == "bitnami_bot" ]]; then
+            # Chart CRDs can be stored at 'bitnami/$CHART/crds' or 'bitnami/$CHART/templates/crds'
+            crd_files="$(find "bitnami/${CHART}/crds" "bitnami/${CHART}/templates/crds" -name "*.yaml" -o -name "*.yml" || true)"
+            for file in "${crd_files[@]}"; do
+              # Validate that the first line of the CRD file includes the entry "#Source: <url>"
+              source_url_tpl="$(head -n 1 $file | grep -Eo "^#Source: ?" | cut -d":" -f2 || true)"
+              if [[ -z "$source_url_tpl" ]]; then
+                echo "error=CRD file '${file}' does not include the '#Source: <url> header'"
+                exit "$exit_code"
+              fi
+              # Validate that the source URL contains the '{version}' placeholder
+              app_dir="$(dirname "$file" | grep -o "bitnami/[^/]*" || true)"
+              if [[ "$source_url_tpl" =~ "{version}" ]]; then
+                source_url=$(echo "$source_url_tpl" | sed "s/{version}/${APP_VERSION}/")
+              else
+                echo "error=Placeholder '{version}' not found in Source url"
+                exit "$exit_code"
+              fi
+              # Validate Second line of the CRD file includes the version of the CRD
+              crd_version="$(head -n 2 $file | tail -n 1 | grep -Eo "^#Version: ?" | cut -d":" -f2 || true)"
+              if [[ -z "$crd_version" ]]; then
+                echo "error=CRD file '${file}' does not include the '#Version: <version> header'"
+                exit "$exit_code"
+              fi
+              # Validate Second line of the CRD file includes the version of the CRD
+              crd_version="$(head -n 2 $file | tail -n 1 | grep -Eo "^#Version: ?" | cut -d":" -f2 || true)"
+              if [[ -z "$crd_version" ]]; then
+                echo "error=CRD file '${file}' does not include the '#Version: <version> header'"
+                exit "$exit_code"
+              fi
+              # If the application version is newer, automatically update the CRD file
+              if [[ "$APP_VERSION" != "$crd_version" ]]; then
+                curl -Lks --fail -o $file "$source_url"
+                sed -i "1s/^/#Source: ${source_url_tpl}\n#Version: ${APP_VERSION}\n/" $file
+                echo "info=CRD file '${file}' automatically updated using source '$source_url'"
+              fi
+            done
+            # Commit all changes, if any
+            if git status -s | grep "bitnami/${CHART}"; then
+              git add "bitnami/${CHART}" && git commit -m "Update CRDs automatically" --signoff
+            fi
+          fi
+      - name: Push changes
+        run: |
+          # Push all the new commits, if any
+          if [[ $(git cherry -v) ]]; then
+            git push
+            echo "changes-pushed=true" >> $GITHUB_OUTPUT
+          else
+            echo "changes-pushed=false" >> $GITHUB_OUTPUT
+          fi
   vib-verify:
     runs-on: ubuntu-latest
-    needs: get-chart
+    needs: [get-chart, update-pr]
     permissions:
       contents: read
     # Given performance issues of the action feature on GH's side, we need to be very restrictive in the job's triggers:
     # -> The 'Get modified charts' job suceededs AND
+    # -> The 'Update PR' job did not push any new changes AND
     #  ( ---> The pipeline was triggered due to a label addition and said label was the 'verify' one OR
     #    ---> the PR already contains the 'verify' label )
     if: |
+      needs.update-pr.outputs.changes-pushed == 'false' &&
       needs.get-chart.outputs.result == 'ok' &&
       (
         contains(github.event.pull_request.labels.*.name, 'verify') || (github.event.action == 'labeled' && github.event.label.name == 'verify')
