CI: Add GH action to ensure no unprintable characters
Signed-off-by: juan131 <jariza@vmware.com>

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -145,6 +145,12 @@ jobs:
               echo "error=Please ensure all *.tag params are skipped (@skip) in the bitnami/${CHART}/values.yaml file"
               exit "$exit_code"
             fi
+            # Ensuring no Unicode characters are present in values.yaml
+            ! grep -q "[^[:print:]]" "bitnami/${CHART}/values.yaml" || exit_code=$?
+            if [[ $exit_code -ne 0 ]]; then
+              echo "error=Please ensure there are no Unicode characters in the bitnami/${CHART}/values.yaml file"
+              exit "$exit_code"
+            fi
             echo "Updating README.md for bitnami/${CHART}"
             readme-generator --values "bitnami/${CHART}/values.yaml" --readme "bitnami/${CHART}/README.md" --schema "/tmp/schema.json"
             # Commit all changes, if any
