[bitnami/*] Skip image's tag in the README files of the Bitnami Charts
Signed-off-by: Jota Martos <jotamartos@vmware.com>

diff --git a/.github/workflows/generate-chart-readme.yml b/.github/workflows/generate-chart-readme.yml
--- a/.github/workflows/generate-chart-readme.yml
+++ b/.github/workflows/generate-chart-readme.yml
@@ -39,23 +39,30 @@ jobs:
           charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep -o "bitnami/[^/]*" | sort | uniq || true)"
           for chart in ${charts_dirs_changed}; do
             echo "Validating README.md for ${chart}"
+            # Validating *.registry parameters
             while read line; do
               echo "$line" | grep --quiet "\[default: \(REGISTRY_NAME\|\"\"\)\]" || exit_code=$?
-            done < <(grep "@param\s\+[A-Za-z\.-]\+\.registry\s\+" "charts/${chart}/values.yaml")
+            done < <(grep "@param\s\+[A-Za-z\.]\+\.registry\s\+" "charts/${chart}/values.yaml")
             if [[ $exit_code -ne 0 ]]; then
               echo "::error:: Please ensure all *.registry params include the [default: REGISTRY_NAME] modifier the ${chart}/values.yaml file"
               exit "$exit_code"
             fi
+            # Validating *.repository parameters
             while read line; do
               param=$(echo "$line" | awk '{print $3}')
               # Checking if it's a image's registry-related param
               registry_param=$(echo ${param} | sed 's/\.repository/\.registry/g')
               grep --quiet "@param\s\+${registry_param}" "${c}/values.yaml" && ( echo "$line" | grep --quiet "\[default: \(REPOSITORY_NAME/.*\|\"\"\)\]" || exit_code=$? )
               echo "$line" | grep --quiet "\[default: \(REPOSITORY_NAME/.*\|\"\"\)\]" || exit_code=$?
-            done < <(grep "@param\s\+[A-Za-z\.-]\+\.repository\s\+" "charts/${chart}/values.yaml")
-            echo "$exit_code"
+            done < <(grep "@param\s\+[A-Za-z\.]\+\.repository\s\+" "charts/${chart}/values.yaml")
             if [[ $exit_code -ne 0 ]]; then
               echo "::error:: Please ensure all *.repository params include the [default: REPOSITORY_NAME] modifier the ${chart}/values.yaml file"
+              exit "$exit_code"
+            fi
+            # Validating *.tag parameters
+            ! grep --quiet "@param\s\+[A-Za-z\.]\+\.tag\s\+" "charts/${chart}/values.yaml" || exit_code=$?
+            if [[ $exit_code -ne 0 ]]; then
+              echo "::error:: Please ensure all *.tag params are skipped (@skip) in the charts/${chart}/values.yaml file"
               exit "$exit_code"
             fi
             echo "Updating README.md for ${chart}"
