Apply some fixes
Signed-off-by: Fran Mulero <fmulero@vmware.com>

diff --git a/.github/workflows/markdown-linter.yml b/.github/workflows/markdown-linter.yml
--- a/.github/workflows/markdown-linter.yml
+++ b/.github/workflows/markdown-linter.yml
@@ -1,6 +1,6 @@
 name: '[CI/CD] Markdown linter'
 on:
-  pull_request_target:
+  pull_request:
     branches:
       - main
     paths:
@@ -12,7 +12,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Install mardownlint
-        run: npm install -g markdownlint-cli
+        run: npm install -g markdownlint-cli@0.32.2
       - name: Checkout bitnami/charts
         uses: actions/checkout@v3
       - name: Execute markdownlint
@@ -23,20 +23,25 @@ jobs:
           files_changed_data=$(curl -s --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -X GET -G "$URL")
           files_changed="$(echo "$files_changed_data" | jq -r '.[] | .filename')"
           md_files="$(echo "$files_changed" | grep -o ".*\.md$" | sort | uniq || true)"
-          markdownlint ${md_files[@]} -o /tmp/output
+          exit_code=0
+          markdownlint -o ${{runner.temp}}/output ${md_files[@]} || exit_code=$?
           while read -r line; do
             # line format:
             #   file:row[:column] message
-            # white space insisde brackets is intentional to detect the message for the notice.
+            # white space inside brackets is intentional to detect the message for the notice.
             message="${line#*[ ]}"
             file_row_column="${line%%[ ]*}"
             # Split by ':'
-            readarray -d : -t strarr <<< "$file_row_column"
+            readarray -d : -t strarr < <(printf '%s' "$file_row_column")
             if [[ "${#strarr[@]}" -eq 3 ]]; then
-              echo "::notice file=${strarr[0]},line=${strarr[1]},col=${strarr[2]}::${message}"
+              echo "::warning file=${strarr[0]},line=${strarr[1]},col=${strarr[2]}::${message}"
             elif [[ "${#strarr[@]}" -eq 2 ]]; then
-              echo "::notice file=${strarr[0]},line=${strarr[1]}::${message}"
+              echo "::warning file=${strarr[0]},line=${strarr[1]}::${message}"
             else
               echo "::warning:: Error processing: ${line}"
             fi
-          done < /tmp/output
+          done < ${{runner.temp}}/output
+          if [[ $exit_code -ne 0 ]]; then
+            echo "::error:: Please review linter messages"
+            exit "$exit_code"
+          fi
