add true
Signed-off-by: Javier Salmeron Garcia <jsalmeron@vmware.com>

diff --git a/.github/workflows/vib-verify.yaml b/.github/workflows/vib-verify.yaml
--- a/.github/workflows/vib-verify.yaml
+++ b/.github/workflows/vib-verify.yaml
@@ -31,14 +31,15 @@ jobs:
       - id: get-chart
         run: |
           files_changed="$(git diff --name-only origin/master HEAD)"
-          charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep "bitnami/"| sort | uniq)"
+          charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep "bitnami/"| sort | uniq || true)"
           # Using grep -c as a better alternative to wc -l when dealing with empty strings
-          num_charts_changed="$(echo "$charts_dirs_changed" | grep -c "bitnami")"
-          num_charts_yaml_changed="$(echo "$files_changed" | grep -c "Chart.yaml")"
+          num_charts_changed="$(echo "$charts_dirs_changed" | grep -c "bitnami" || true)"
+          num_charts_yaml_changed="$(echo "$files_changed" | grep -c "Chart.yaml" || true)"
 
-          if [[ "$num_charts_changed" -eq "$num_charts_yaml_changed" ]]; then
+          if [[ "$num_charts_changed" -ne "$num_charts_yaml_changed" ]]; then
             # Changes done in charts but version not bumped -> ERROR
-            echo HIIII
+            echo -e "::set-output name=error::Detected changes in charts without bump in Chart.yaml.\nCharts changed:\n ${charts_dirs_changed}\nChart.yaml changes detected: ${num_charts_yaml_changed}"
+            echo "::set-output name=result::fail"
           elif [[ "$num_charts_changed" -eq "1" ]]; then
             # Changes done in only one chart -> OK
             echo "::set-output name=chart::${charts_dirs_changed}"
