Change version
Signed-off-by: Javier Salmeron Garcia <jsalmeron@vmware.com>

diff --git a/.github/workflows/vib-verify.yaml b/.github/workflows/vib-verify.yaml
--- a/.github/workflows/vib-verify.yaml
+++ b/.github/workflows/vib-verify.yaml
@@ -35,11 +35,11 @@ jobs:
           charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep "bitnami/"| sort | uniq || true)"
           # Using grep -c as a better alternative to wc -l when dealing with empty strings."
           num_charts_changed="$(echo "$charts_dirs_changed" | grep -c "bitnami" || true)"
-          num_charts_yaml_changed="$(echo "$files_changed" | grep -c "Chart.yaml" || true)"
+          num_version_bumps="$(echo "$charts_dirs_changed" | grep Chart.yaml | xargs git diff origin/master | grep -c "+version" || true)"
 
-          if [[ "$num_charts_changed" -ne "$num_charts_yaml_changed" ]]; then
+          if [[ "$num_charts_changed" -ne "$num_version_bumps" ]]; then
             # Changes done in charts but version not bumped -> ERROR
-            echo -e "::set-output name=error::Detected changes in charts without bump in Chart.yaml.\nCharts changed:\n ${charts_dirs_changed}\nChart.yaml changes detected: ${num_charts_yaml_changed}"
+            echo -e "::set-output name=error::Detected changes in charts without bump in Chart.yaml.\nCharts changed:\n ${charts_dirs_changed}\nVersion bumps detected: ${num_version_bumps}"
             echo "::set-output name=result::fail"
           elif [[ "$num_charts_changed" -eq "1" ]]; then
             # Changes done in only one chart -> OK
